"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Callable, List, Optional, Tuple, Union
from ..font import CTkFont
from ..appearance_mode import CTkAppearanceModeBaseClass
from ..scaling import CTkScalingBaseClass

class DropdownMenu(tkinter.Menu, CTkAppearanceModeBaseClass, CTkScalingBaseClass):
    def __init__(self, *args, min_character_width: int = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., hover_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color: Optional[Union[str, Tuple[str, str]]] = ..., font: Optional[Union[tuple, CTkFont]] = ..., command: Union[Callable, None] = ..., values: Optional[List[str]] = ..., **kwargs) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def open(self, x: Union[int, float], y: Union[int, float]): # -> None:
        ...
    
    def configure(self, **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    


