"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Optional, Tuple, Union
from .widgets.scaling import CTkScalingBaseClass
from .widgets.appearance_mode import CTkAppearanceModeBaseClass

CTK_PARENT_CLASS = tkinter.Tk
class CTk(CTK_PARENT_CLASS, CTkAppearanceModeBaseClass, CTkScalingBaseClass):
    """
    Main app window with dark titlebar on Windows and macOS.
    For detailed information check out the documentation.
    """
    _valid_tk_constructor_arguments: set = ...
    _valid_tk_configure_arguments: set = ...
    _deactivate_macos_window_header_manipulation: bool = ...
    _deactivate_windows_window_header_manipulation: bool = ...
    def __init__(self, fg_color: Optional[Union[str, Tuple[str, str]]] = ..., **kwargs) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def block_update_dimensions_event(self): # -> None:
        ...
    
    def unblock_update_dimensions_event(self): # -> None:
        ...
    
    def withdraw(self): # -> None:
        ...
    
    def iconify(self): # -> None:
        ...
    
    def update(self): # -> None:
        ...
    
    def mainloop(self, *args, **kwargs): # -> None:
        ...
    
    def resizable(self, width: bool = ..., height: bool = ...): # -> None:
        ...
    
    def minsize(self, width: int = ..., height: int = ...): # -> None:
        ...
    
    def maxsize(self, width: int = ..., height: int = ...): # -> None:
        ...
    
    def geometry(self, geometry_string: str = ...): # -> None:
        ...
    
    def configure(self, **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def wm_iconbitmap(self, bitmap=..., default=...): # -> None:
        ...
    
    def iconbitmap(self, bitmap=..., default=...): # -> None:
        ...
    


