"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple, Union
from .ctk_toplevel import CTkToplevel
from .widgets.font import CTkFont

class CTkInputDialog(CTkToplevel):
    """
    Dialog with extra window, message, entry widget, cancel and ok button.
    For detailed information check out the documentation.
    """
    def __init__(self, fg_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color: Optional[Union[str, Tuple[str, str]]] = ..., button_fg_color: Optional[Union[str, Tuple[str, str]]] = ..., button_hover_color: Optional[Union[str, Tuple[str, str]]] = ..., button_text_color: Optional[Union[str, Tuple[str, str]]] = ..., entry_fg_color: Optional[Union[str, Tuple[str, str]]] = ..., entry_border_color: Optional[Union[str, Tuple[str, str]]] = ..., entry_text_color: Optional[Union[str, Tuple[str, str]]] = ..., title: str = ..., font: Optional[Union[tuple, CTkFont]] = ..., text: str = ...) -> None:
        ...
    
    def get_input(self): # -> str | None:
        ...
    


