"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Optional, Tuple, Union
from .widgets.scaling import CTkScalingBaseClass
from .widgets.appearance_mode import CTkAppearanceModeBaseClass

class CTkToplevel(tkinter.Toplevel, CTkAppearanceModeBaseClass, CTkScalingBaseClass):
    """
    Toplevel window with dark titlebar on Windows and macOS.
    For detailed information check out the documentation.
    """
    _valid_tk_toplevel_arguments: set = ...
    _deactivate_macos_window_header_manipulation: bool = ...
    _deactivate_windows_window_header_manipulation: bool = ...
    def __init__(self, *args, fg_color: Optional[Union[str, Tuple[str, str]]] = ..., **kwargs) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def block_update_dimensions_event(self): # -> None:
        ...
    
    def unblock_update_dimensions_event(self): # -> None:
        ...
    
    def geometry(self, geometry_string: str = ...): # -> None:
        ...
    
    def withdraw(self): # -> None:
        ...
    
    def iconify(self): # -> None:
        ...
    
    def resizable(self, width: bool = ..., height: bool = ...): # -> None:
        ...
    
    def minsize(self, width=..., height=...): # -> None:
        ...
    
    def maxsize(self, width=..., height=...): # -> None:
        ...
    
    def configure(self, **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def wm_iconbitmap(self, bitmap=..., default=...): # -> None:
        ...
    


