"""
This type stub file was generated by pyright.
"""

def pop_from_dict_by_set(dictionary: dict, valid_keys: set) -> dict:
    """ remove and create new dict with key value pairs of dictionary, where key is in valid_keys """
    ...

def check_kwargs_empty(kwargs_dict, raise_error=...) -> bool:
    """ returns True if kwargs are empty, False otherwise, raises error if not empty """
    ...

