"""
This type stub file was generated by pyright.
"""

from typing import Callable

class AppearanceModeTracker:
    callback_list = ...
    app_list = ...
    update_loop_running = ...
    update_loop_interval = ...
    appearance_mode_set_by = ...
    appearance_mode = ...
    @classmethod
    def init_appearance_mode(cls): # -> None:
        ...
    
    @classmethod
    def add(cls, callback: Callable, widget=...): # -> None:
        ...
    
    @classmethod
    def remove(cls, callback: Callable): # -> None:
        ...
    
    @staticmethod
    def detect_appearance_mode() -> int:
        ...
    
    @classmethod
    def get_tk_root_of_widget(cls, widget):
        ...
    
    @classmethod
    def update_callbacks(cls): # -> None:
        ...
    
    @classmethod
    def update(cls): # -> None:
        ...
    
    @classmethod
    def get_mode(cls) -> int:
        ...
    
    @classmethod
    def set_appearance_mode(cls, mode_string: str): # -> None:
        ...
    


