"""
This type stub file was generated by pyright.
"""

class CTkAppearanceModeBaseClass:
    """
    Super-class that manages the appearance mode. Methods:

    - destroy() must be called when sub-class is destroyed
    - _set_appearance_mode() abstractmethod, gets called when appearance mode changes, must be overridden
    - _apply_appearance_mode() to convert tuple color

    """
    def __init__(self) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    


