"""
This type stub file was generated by pyright.
"""

import os
import sys
from .ctk_font import CTkFont
from .font_manager import FontManager
from ..core_rendering import DrawEngine

customtkinter_directory = ...
if FontManager.load_font(os.path.join(customtkinter_directory, "assets", "fonts", "CustomTkinter_shapes_font.otf")) is False:
    ...
