"""
This type stub file was generated by pyright.
"""

from typing import Union

class FontManager:
    linux_font_path = ...
    @classmethod
    def init_font_manager(cls): # -> bool:
        ...
    
    @classmethod
    def windows_load_font(cls, font_path: Union[str, bytes], private: bool = ..., enumerable: bool = ...) -> bool:
        """ Function taken from: https://stackoverflow.com/questions/11993290/truly-custom-font-in-tkinter/30631309#30631309 """
        ...
    
    @classmethod
    def load_font(cls, font_path: str) -> bool:
        ...
    


