"""
This type stub file was generated by pyright.
"""

from typing import Callable, Tuple
from PIL import Image, ImageTk

class CTkImage:
    """
    Class to store one or two PIl.Image.Image objects and display size independent of scaling:

    light_image: PIL.Image.Image for light mode
    dark_image: PIL.Image.Image for dark mode
    size: tuple (<width>, <height>) with display size for both images

    One of the two images can be None and will be replaced by the other image.
    """
    _checked_PIL_import = ...
    def __init__(self, light_image: Image.Image = ..., dark_image: Image.Image = ..., size: Tuple[int, int] = ...) -> None:
        ...
    
    def add_configure_callback(self, callback: Callable): # -> None:
        """ add function, that gets called when image got configured """
        ...
    
    def remove_configure_callback(self, callback: Callable): # -> None:
        """ remove function, that gets called when image got configured """
        ...
    
    def configure(self, **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def create_scaled_photo_image(self, widget_scaling: float, appearance_mode: str) -> ImageTk.PhotoImage:
        ...
    


