"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Tuple, Union
from .core_widget_classes import CTkBaseClass

class CTkFrame(CTkBaseClass):
    """
    Frame with rounded corners and border.
    Default foreground colors are set according to theme.
    To make the frame transparent set fg_color=None.
    For detailed information check out the documentation.
    """
    def __init__(self, master: Any, width: int = ..., height: int = ..., corner_radius: Optional[Union[int, str]] = ..., border_width: Optional[Union[int, str]] = ..., bg_color: Union[str, Tuple[str, str]] = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., border_color: Optional[Union[str, Tuple[str, str]]] = ..., background_corner_colors: Union[Tuple[Union[str, Tuple[str, str]]], None] = ..., overwrite_preferred_drawing_method: Union[str, None] = ..., **kwargs) -> None:
        ...
    
    def winfo_children(self) -> List[any]:
        """
        winfo_children of CTkFrame without self.canvas widget,
        because it's not a child but part of the CTkFrame itself
        """
        ...
    
    def configure(self, require_redraw=..., **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def bind(self, sequence=..., command=..., add=...): # -> None:
        """ called on the tkinter.Canvas """
        ...
    
    def unbind(self, sequence=..., funcid=...): # -> None:
        """ called on the tkinter.Canvas """
        ...
    


