"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Any, Callable, Optional, Tuple, Union
from .core_widget_classes import CTkBaseClass
from .font import CTkFont
from .image import CTkImage

class CTkButton(CTkBaseClass):
    """
    Button with rounded corners, border, hover effect, image support, click command and textvariable.
    For detailed information check out the documentation.
    """
    _image_label_spacing: int = ...
    def __init__(self, master: Any, width: int = ..., height: int = ..., corner_radius: Optional[int] = ..., border_width: Optional[int] = ..., border_spacing: int = ..., bg_color: Union[str, Tuple[str, str]] = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., hover_color: Optional[Union[str, Tuple[str, str]]] = ..., border_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color_disabled: Optional[Union[str, Tuple[str, str]]] = ..., background_corner_colors: Union[Tuple[Union[str, Tuple[str, str]]], None] = ..., round_width_to_even_numbers: bool = ..., round_height_to_even_numbers: bool = ..., text: str = ..., font: Optional[Union[tuple, CTkFont]] = ..., textvariable: Union[tkinter.Variable, None] = ..., image: Union[CTkImage, ImageTk.PhotoImage, None] = ..., state: str = ..., hover: bool = ..., command: Union[Callable[[], Any], None] = ..., compound: str = ..., anchor: str = ..., **kwargs) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def configure(self, require_redraw=..., **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def invoke(self): # -> None:
        """ calls command function if button is not disabled """
        ...
    
    def bind(self, sequence: str = ..., command: Callable = ..., add: Union[str, bool] = ...): # -> None:
        """ called on the tkinter.Canvas """
        ...
    
    def unbind(self, sequence: str = ..., funcid: str = ...):
        """ called on the tkinter.Label and tkinter.Canvas """
        ...
    
    def focus(self): # -> None:
        ...
    
    def focus_set(self): # -> None:
        ...
    
    def focus_force(self): # -> None:
        ...
    


