"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Any, Callable, Optional, Tuple, Union
from .core_widget_classes import CTkBaseClass

class CTkSlider(CTkBaseClass):
    """
    Slider with rounded corners, border, number of steps, variable support, vertical orientation.
    For detailed information check out the documentation.
    """
    def __init__(self, master: Any, width: Optional[int] = ..., height: Optional[int] = ..., corner_radius: Optional[int] = ..., button_corner_radius: Optional[int] = ..., border_width: Optional[int] = ..., button_length: Optional[int] = ..., bg_color: Union[str, Tuple[str, str]] = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., border_color: Union[str, Tuple[str, str]] = ..., progress_color: Optional[Union[str, Tuple[str, str]]] = ..., button_color: Optional[Union[str, Tuple[str, str]]] = ..., button_hover_color: Optional[Union[str, Tuple[str, str]]] = ..., from_: int = ..., to: int = ..., state: str = ..., number_of_steps: Union[int, None] = ..., hover: bool = ..., command: Union[Callable[[float], Any], None] = ..., variable: Union[tkinter.Variable, None] = ..., orientation: str = ..., **kwargs) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def configure(self, require_redraw=..., **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def get(self) -> float:
        ...
    
    def set(self, output_value, from_variable_callback=...): # -> None:
        ...
    
    def bind(self, sequence: str = ..., command: Callable = ..., add: Union[str, bool] = ...): # -> None:
        """ called on the tkinter.Canvas """
        ...
    
    def unbind(self, sequence: str = ..., funcid: str = ...):
        """ called on the tkinter.Label and tkinter.Canvas """
        ...
    
    def focus(self):
        ...
    
    def focus_set(self): # -> None:
        ...
    
    def focus_force(self): # -> None:
        ...
    


