"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Any, Literal, Optional, Tuple, Union
from .appearance_mode import CTkAppearanceModeBaseClass
from .scaling import CTkScalingBaseClass
from .font import CTkFont

class CTkScrollableFrame(tkinter.Frame, CTkAppearanceModeBaseClass, CTkScalingBaseClass):
    def __init__(self, master: Any, width: int = ..., height: int = ..., corner_radius: Optional[Union[int, str]] = ..., border_width: Optional[Union[int, str]] = ..., bg_color: Union[str, Tuple[str, str]] = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., border_color: Optional[Union[str, Tuple[str, str]]] = ..., scrollbar_fg_color: Optional[Union[str, Tuple[str, str]]] = ..., scrollbar_button_color: Optional[Union[str, Tuple[str, str]]] = ..., scrollbar_button_hover_color: Optional[Union[str, Tuple[str, str]]] = ..., label_fg_color: Optional[Union[str, Tuple[str, str]]] = ..., label_text_color: Optional[Union[str, Tuple[str, str]]] = ..., label_text: str = ..., label_font: Optional[Union[tuple, CTkFont]] = ..., label_anchor: str = ..., orientation: Literal["vertical", "horizontal"] = ...) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def configure(self, **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str): # -> int | str:
        ...
    
    def check_if_master_is_canvas(self, widget): # -> bool:
        ...
    
    def pack(self, **kwargs): # -> None:
        ...
    
    def place(self, **kwargs): # -> None:
        ...
    
    def grid(self, **kwargs): # -> None:
        ...
    
    def pack_forget(self): # -> None:
        ...
    
    def place_forget(self, **kwargs): # -> None:
        ...
    
    def grid_forget(self, **kwargs): # -> None:
        ...
    
    def grid_remove(self, **kwargs): # -> None:
        ...
    
    def grid_propagate(self, **kwargs): # -> None:
        ...
    
    def grid_info(self, **kwargs): # -> _GridInfo:
        ...
    
    def lift(self, aboveThis=...): # -> None:
        ...
    
    def lower(self, belowThis=...): # -> None:
        ...
    


