"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Any, Callable, Optional, Tuple, Union
from .font import CTkFont
from .ctk_frame import CTkFrame

class CTkSegmentedButton(CTkFrame):
    """
    Segmented button with corner radius, border width, variable support.
    For detailed information check out the documentation.
    """
    def __init__(self, master: Any, width: int = ..., height: int = ..., corner_radius: Optional[int] = ..., border_width: int = ..., bg_color: Union[str, Tuple[str, str]] = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., selected_color: Optional[Union[str, Tuple[str, str]]] = ..., selected_hover_color: Optional[Union[str, Tuple[str, str]]] = ..., unselected_color: Optional[Union[str, Tuple[str, str]]] = ..., unselected_hover_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color_disabled: Optional[Union[str, Tuple[str, str]]] = ..., background_corner_colors: Union[Tuple[Union[str, Tuple[str, str]]], None] = ..., font: Optional[Union[tuple, CTkFont]] = ..., values: Optional[list] = ..., variable: Union[tkinter.Variable, None] = ..., dynamic_resizing: bool = ..., command: Union[Callable[[str], Any], None] = ..., state: str = ...) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def configure(self, **kwargs):
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def set(self, value: str, from_variable_callback: bool = ..., from_button_callback: bool = ...): # -> None:
        ...
    
    def get(self) -> str:
        ...
    
    def index(self, value: str) -> int:
        ...
    
    def insert(self, index: int, value: str): # -> None:
        ...
    
    def move(self, new_index: int, value: str): # -> None:
        ...
    
    def delete(self, value: str): # -> None:
        ...
    
    def bind(self, sequence=..., command=..., add=...):
        ...
    
    def unbind(self, sequence=..., funcid=...):
        ...
    


