"""
This type stub file was generated by pyright.
"""

import tkinter
from typing import Any, Callable, Optional, Tuple, Union
from .core_widget_classes import CTkBaseClass
from .font import CTkFont

class CTkSwitch(CTkBaseClass):
    """
    Switch with rounded corners, border, label, command, variable support.
    For detailed information check out the documentation.
    """
    def __init__(self, master: Any, width: int = ..., height: int = ..., switch_width: int = ..., switch_height: int = ..., corner_radius: Optional[int] = ..., border_width: Optional[int] = ..., button_length: Optional[int] = ..., bg_color: Union[str, Tuple[str, str]] = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., border_color: Union[str, Tuple[str, str]] = ..., progress_color: Optional[Union[str, Tuple[str, str]]] = ..., button_color: Optional[Union[str, Tuple[str, str]]] = ..., button_hover_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color_disabled: Optional[Union[str, Tuple[str, str]]] = ..., text: str = ..., font: Optional[Union[tuple, CTkFont]] = ..., textvariable: Union[tkinter.Variable, None] = ..., onvalue: Union[int, str] = ..., offvalue: Union[int, str] = ..., variable: Union[tkinter.Variable, None] = ..., hover: bool = ..., command: Union[Callable, Any] = ..., state: str = ..., **kwargs) -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def configure(self, require_redraw=..., **kwargs): # -> None:
        ...
    
    def cget(self, attribute_name: str) -> any:
        ...
    
    def toggle(self, event=...): # -> None:
        ...
    
    def select(self, from_variable_callback=...): # -> None:
        ...
    
    def deselect(self, from_variable_callback=...): # -> None:
        ...
    
    def get(self) -> Union[int, str]:
        ...
    
    def bind(self, sequence: str = ..., command: Callable = ..., add: Union[str, bool] = ...): # -> None:
        """ called on the tkinter.Canvas """
        ...
    
    def unbind(self, sequence: str = ..., funcid: str = ...):
        """ called on the tkinter.Label and tkinter.Canvas """
        ...
    
    def focus(self): # -> None:
        ...
    
    def focus_set(self): # -> None:
        ...
    
    def focus_force(self): # -> None:
        ...
    


