"""
This type stub file was generated by pyright.
"""

import sys
from .scaling_base_class import CTkScalingBaseClass
from .scaling_tracker import ScalingTracker

if sys.platform.startswith("win") and sys.getwindowsversion().build < 9000:
    ...
