"""
This type stub file was generated by pyright.
"""

from typing import List, Union

class ThemeManager:
    theme: dict = ...
    _built_in_themes: List[str] = ...
    _currently_loaded_theme: Union[str, None] = ...
    @classmethod
    def load_theme(cls, theme_name_or_path: str): # -> None:
        ...
    
    @classmethod
    def save_theme(cls): # -> None:
        ...
    


