"""
This type stub file was generated by pyright.
"""

import os
import sys
import tkinter.filedialog as filedialog
from tkinter import BooleanVar, DoubleVar, IntVar, StringVar, Variable
from tkinter.constants import *
from .windows.widgets.appearance_mode import AppearanceModeTracker
from .windows.widgets.font import CTkFont, FontManager
from .windows.widgets.scaling import ScalingTracker
from .windows.widgets.theme import ThemeManager
from .windows.widgets.core_rendering import CTkCanvas, DrawEngine
from .windows.widgets.core_widget_classes import CTkBaseClass
from .windows.widgets import CTkButton, CTkCheckBox, CTkComboBox, CTkEntry, CTkFrame, CTkLabel, CTkOptionMenu, CTkProgressBar, CTkRadioButton, CTkScrollableFrame, CTkScrollbar, CTkSegmentedButton, CTkSlider, CTkSwitch, CTkTabview, CTkTextbox
from .windows import CTk, CTkInputDialog, CTkToplevel, ctk_tk
from .windows.widgets.image import CTkImage

__version__ = ...
_ = ...
def set_appearance_mode(mode_string: str): # -> None:
    """ possible values: light, dark, system """
    ...

def get_appearance_mode() -> str:
    """ get current state of the appearance mode (light or dark) """
    ...

def set_default_color_theme(color_string: str): # -> None:
    """ set color theme or load custom theme file by passing the path """
    ...

def set_widget_scaling(scaling_value: float): # -> None:
    """ set scaling for the widget dimensions """
    ...

def set_window_scaling(scaling_value: float): # -> None:
    """ set scaling for window dimensions """
    ...

def deactivate_automatic_dpi_awareness(): # -> None:
    """ deactivate DPI awareness of current process (windll.shcore.SetProcessDpiAwareness(0)) """
    ...

def set_ctk_parent_class(ctk_parent_class): # -> None:
    ...

